# Generated by Django 6.0.5 on 2026-05-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='temp', unique=True, verbose_name='Слаг (для URL)'),
            preserve_default=False,
        ),
    ]
